[package]
name = "master"
version = "0.1.0"
edition = "2021"

[dependencies]
qt4004core = { path = "../qt4004core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", features = ["full"] }
warp = "0.3"

